WIDTH = 400
HEIGHT = 500

CELL_SIZE = 20
CELL_NUMBER = 15
GAME_SIZE = CELL_SIZE * CELL_NUMBER
W_OFFSET = (WIDTH - GAME_SIZE) / 2
H_OFFSET = (HEIGHT - GAME_SIZE) / 2

WHITE = 'white'
BLACK = 'black'
RED = 'red'
